image: electronuserland/builder:wine
before_script:
  - node -v
stages:
  - build
build:
  stage: build
  script:
    - npm install
    - npm run compile
    - npm run build-win
    - npm run build-linux
  artifacts:
    paths:
      - installer/
    expire_in: 1 week
