image: electronuserland/electron-builder:latest
pipelines:
  custom: # Pipelines that can only be triggered manually
    manual: # The name that is displayed in the list in the Bitbucket Cloud GUI
      - step:
          name: Build
          caches:
              - node
          script:
              - npm install
              - npm run compile
              - npm run build-win
              - npm run build-linux
          artifacts:
              - installer/**
