image: node:12.13.0
pipelines:
  custom: # Pipelines that can only be triggered manually
    manual: # The name that is displayed in the list in the Bitbucket Cloud GUI
      - step:
          name: Dependencies installation (Wine)
          script:
                - echo "deb http://httpredir.debian.org/debian jessie-backports main" >> /etc/apt/sources.list
                - dpkg --add-architecture i386
                - apt-get update && apt-get install -y wine
      - step:
          name: Build
          caches:
              - node
          script:
              - npm install
              - npm run compile
              - npm run build-win
              - npm run build-linux
          artifacts:
              - installer/**
