image: node:12.13.0
pipelines:
  custom: # Pipelines that can only be triggered manually
    manual: # The name that is displayed in the list in the Bitbucket Cloud GUI
      - step:
          name: Dependencies installation (Wine)
          script:
                - dpkg --add-architecture i386
                - wget -nc https://dl.winehq.org/wine-builds/winehq.key
                - apt-key add winehq.key
                - add-apt-repository 'deb https://dl.winehq.org/wine-builds/ubuntu/ focal main'
                - sudo apt update
                - sudo apt install --install-recommends winehq-stable
      - step:
          name: Build
          caches:
              - node
          script:
              - npm install
              - npm run compile
              - npm run build-win
              - npm run build-linux
          artifacts:
              - installer/**
