image: scottyhardy/docker-wine:latest
pipelines:
  custom: # Pipelines that can only be triggered manually
    manual: # The name that is displayed in the list in the Bitbucket Cloud GUI
      - step:
          name: Dependencies installation (Node)
          script:
                - curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
                - sudo apt-get install -y nodejs
      - step:
          name: Build
          caches:
              - node
          script:
              - npm install
              - npm run compile
              - npm run build-win
              - npm run build-linux
          artifacts:
              - installer/**
